### ISSUE TITLE
inputs.js

### ISSUE THREAD

**Issue by storypixel** [mariotacke/advent-of-code-2018#1]
Hi, I am really impressed by your clean approach. I am relatively new to this, I see your tests... but I was wondering how you are running your methods against the aoc inputs?

**Comment by mariotacke** [comment]
hi @storypixel; glad you like it, i usually create an `input.js` file in every day subfolder, usually in this format:

```
const input = 
`<copy paste input from site>`;

console.log(require('./day-module')(input));
console.loh(require('./day-module2')(input));
```

Notice the double \` (back tick) for my input. That way, you can copy paste multi-line inputs. This is also the reason why most of my modules start with parsing the input via `input.split('\n').map(...)`. Hope that makes sense.

**Comment by mariotacke** [comment]
Let me know if you have any more questions! Closing this for now.

**Comment by storypixel** [comment]
thanks!!
